# Generated by Django 3.2.9 on 2022-02-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itime', models.IntegerField()),
                ('port_num', models.IntegerField()),
                ('baud_rate', models.IntegerField()),
                ('sms_status', models.BooleanField()),
            ],
        ),
    ]
