# Generated by Django 3.2.9 on 2022-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0002_sms_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('mpaswd', models.CharField(max_length=50)),
                ('smtp_server', models.CharField(max_length=50)),
                ('smtp_port', models.IntegerField()),
                ('ssl', models.CharField(max_length=50)),
                ('mail_status', models.BooleanField()),
            ],
        ),
    ]
