# Generated by Django 3.2.9 on 2022-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0003_mail_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('t1inv', models.DateTimeField()),
                ('t1activ', models.BooleanField()),
                ('t2inv', models.DateTimeField()),
                ('t2activ', models.BooleanField()),
                ('t3inv', models.DateTimeField()),
                ('t3activ', models.BooleanField()),
                ('t4inv', models.DateTimeField()),
                ('t4activ', models.BooleanField()),
                ('t5inv', models.DateTimeField()),
                ('t5activ', models.BooleanField()),
                ('db_path', models.CharField(max_length=50)),
                ('bkup_status', models.BooleanField()),
                ('lastdatabckup', models.DateTimeField()),
            ],
        ),
    ]
