# Generated by Django 3.2.9 on 2022-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0004_db_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_setting',
            name='bkup_status',
            field=models.CharField(max_length=50),
        ),
    ]
