# Generated by Django 3.2.9 on 2022-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0005_alter_db_setting_bkup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_select', models.CharField(max_length=30)),
                ('admin_page', models.CharField(max_length=100)),
                ('supervise_page', models.CharField(max_length=100)),
                ('audit_page', models.CharField(max_length=100)),
                ('master_page', models.CharField(max_length=100)),
                ('history_page', models.CharField(max_length=100)),
                ('help_page', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='operator_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_page', models.CharField(max_length=100)),
                ('supervise_page', models.CharField(max_length=100)),
                ('audit_page', models.CharField(max_length=100)),
                ('master_page', models.CharField(max_length=100)),
                ('history_page', models.CharField(max_length=100)),
                ('help_page', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='supervise_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_page', models.CharField(max_length=100)),
                ('supervise_page', models.CharField(max_length=100)),
                ('audit_page', models.CharField(max_length=100)),
                ('master_page', models.CharField(max_length=100)),
                ('history_page', models.CharField(max_length=100)),
                ('help_page', models.CharField(max_length=100)),
            ],
        ),
    ]
