# Generated by Django 3.2.9 on 2022-02-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0006_admin_group_operator_group_supervise_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_setting',
            name='t1inv',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='db_setting',
            name='t2inv',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='db_setting',
            name='t3inv',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='db_setting',
            name='t4inv',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='db_setting',
            name='t5inv',
            field=models.TimeField(),
        ),
    ]
