# Generated by Django 3.2.9 on 2022-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0010_auto_20220228_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='EquipmentActivationStation',
            field=models.CharField(default='Inactive', max_length=200),
        ),
    ]
