# Generated by Django 3.2.9 on 2022-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0011_equipment_equipmentactivationstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.CharField(default='UserType', max_length=20),
        ),
    ]
