# Generated by Django 3.2.9 on 2022-03-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0012_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(default='DepartmentName', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Department',
        ),
        migrations.AddField(
            model_name='user',
            name='Dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nivdas.department'),
        ),
    ]
