# Generated by Django 3.2.9 on 2022-03-30 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0014_useraudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasesetting',
            name='days',
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 3, 30, 12, 23, 17, 845486)),
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Time',
            field=models.TimeField(default=datetime.time(12, 23, 17, 845486)),
        ),
    ]
