# Generated by Django 3.2.9 on 2022-04-21 22:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0015_auto_20220330_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudit',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 4, 3, 36, 746513)),
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Time',
            field=models.TimeField(default=datetime.time(4, 3, 36, 746513)),
        ),
        migrations.CreateModel(
            name='EqpParameterTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetValue', models.CharField(default='0', max_length=200)),
                ('LowerLimit', models.CharField(default='0', max_length=200)),
                ('UpperLimit', models.CharField(default='0', max_length=200)),
                ('TotalSensor', models.CharField(default='0', max_length=200)),
                ('Cooling', models.CharField(default='Cooling', max_length=200)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivdas.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EqpParameterLux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetLux', models.CharField(default='0', max_length=200)),
                ('SetLuxIntensity', models.CharField(default='0', max_length=200)),
                ('SetUV', models.CharField(default='0', max_length=200)),
                ('SetUVIntensity', models.CharField(default='0', max_length=200)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivdas.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EqpParameterHum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetValue', models.CharField(default='0', max_length=200)),
                ('LowerLimit', models.CharField(default='0', max_length=200)),
                ('UpperLimit', models.CharField(default='0', max_length=200)),
                ('TotalSensor', models.CharField(default='0', max_length=200)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivdas.equipment')),
            ],
        ),
    ]
