# Generated by Django 3.2.9 on 2022-04-26 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0016_auto_20220422_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chm_name', models.CharField(default='chm_name', max_length=100)),
                ('chm_register', models.CharField(default='chm_register', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 12, 26, 19, 897705)),
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Time',
            field=models.TimeField(default=datetime.time(12, 26, 19, 897705)),
        ),
    ]
