# Generated by Django 3.2.9 on 2022-04-26 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0017_auto_20220426_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudit',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 12, 26, 35, 703818)),
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Time',
            field=models.TimeField(default=datetime.time(12, 26, 35, 703818)),
        ),
    ]
