# Generated by Django 3.2.9 on 2022-04-26 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivdas', '0018_auto_20220426_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NumberOfChamber',
            field=models.CharField(default='chamber', max_length=30),
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 14, 4, 35, 523158)),
        ),
        migrations.AlterField(
            model_name='useraudit',
            name='Time',
            field=models.TimeField(default=datetime.time(14, 4, 35, 523158)),
        ),
    ]
